# workflow 名称
name: hub-mirror

# 当新建 issues 时，触发当前 workflow
on:
  issues:
    types:
      - opened

# 需要执行的任务列表
jobs:
  # 镜像转换任务
  mirror_transition:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行条件 => issues 的 label 包含 hub-mirror
    if: contains(github.event.issue.labels.*.name, 'hub-mirror')
    # 镜像转换任务的步骤列表
    steps:
      # 1. 切换分支（默认主分支）
      - name: Check out code
        uses: actions/checkout@v4
      # 2. 设置 python 环境
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # 3. 运行 python 代码
      - name: Install package
        run: |-
            pip install -r requestment.txt -y
            python main.py --content='${{ github.event.issue.body }}'
    